services:
  personal-site:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL:-}
    ports:
      - "3000:80"
    restart: unless-stopped
